#!/usr/bin/env ruby

# Creates or updates the AWS CloudFormation stack for the current environment.
# Requires AWS credentials to be provided in the environment.

require_relative '../deployment'
require 'cdo/rake_utils'
require 'cdo/aws/s3'
require 'cdo/aws/cloud_formation'
require 'aws-sdk'

Aws::S3::Client.new(region: 'us-east-1').put_object(
  bucket: 'cdo-dist',
  key: 'cdo-bootstrap.sh',
  body: File.read('./cdo-chef-bootstrap.sh'),
  acl: 'public-read'
)

CDO.chef_local_mode = true

# Update local-mode cookbooks for this branch
if CDO.chef_local_mode
  RakeUtils.with_bundle_dir(cookbooks_dir) do
    RakeUtils.bundle_exec 'berks', 'package', '/tmp/berks.tar.gz'
    Aws::S3::Client.new(region: 'us-east-1').put_object(
      bucket: 'cdo-dist',
      key: "chef/#{RakeUtils.git_branch}.tar.gz",
      body: File.read('/tmp/berks.tar.gz'),
      acl: 'public-read'
    )
  end
end

AWS::CloudFormation.create_or_update
